#!/bin/bash
HERE=$(dirname $(realpath $(which "$0")))
TODO_ROOT=$(dirname "$HERE")

taskdir_template="$1"

template_name=$(basename "$taskdir_template")
instantiated_template="$TODO_ROOT/new/$template_name"

cp -r "$taskdir_template" "$instantiated_template"
"$instantiated_template"/instantiate
rm "$instantiated_template"/instantiate
