#!/bin/bash
HERE=$(dirname $(realpath $(which "$0")))
source "$HERE"/bash_utils

TODOROOT=$(dirname $(dirname $(realpath $(which "$0"))))
context_header=${1:-''}

PLANNING_FALLACY_PENALTY=1.65 #planning fallacy penalty: assume things will take much longer than you think-- constant to multiply time estimates by

#Accounts for argument --gap=1 not supported by fzf version 0.54.2 used on AMD machine
if cat /etc/os-release 2> /dev/null | grep -q 'NAME="Red Hat Enterprise Linux"'; then #AMD machine
    fzf_gap_arg=''
else #personal machine
    fzf_gap_arg='--gap=1'
fi

#Using fzf for consistent UX experience thru-out task-sys, even tho bash read would be equivalent here
run 'echo "" | fzf --prompt="WRITE_GOAL -- 1-3 concrete sentences >" --header="$context_header" --print-query $fzf_gap_arg'
exit_code=$?

if [ "$exit_code" -gt "1" ] ; then
    echo "ERROR: fzf had unexpected exit code: $exit_code" >&2
	exit "$exit_code"
fi
goal=$(
	echo "$STDOUT" | 
	xargs | #trim leading/trailing whitespace
	sed 's/\s\+/_/g' #replace delimiting whitespace with _
)
if [ -z "$goal" ] ; then #no empty goals allowed
	echo 'ERROR: Goal cannot be empty string.' >&2
	exit 1
fi

estimated_time_suggestions=$(
	echo "0.03       2m"
	echo "0.08       5m"
	echo "0.11       7m"
	echo "0.17       10m"
	echo "0.25       15m"
	echo "0.33       20m"
	echo "0.41       25m"
	echo "0.50       30m"
	echo "0.75       45m"
	echo "1          1h"
	echo "1.25       1h 15m"
	echo "1.50       1h 30m"
	echo "1.75       1h 45m"
	echo "2          2h"
    #anything larger is sus, since it is unlikely to fit within 1 ultradian-- suggests it should prob be broken into separate tasks
	#echo "3          3h"
	#echo "4          4h"
	#echo "5          5h"
	#echo "6          6h"
	#echo "7          7h"
	#echo "8          8h"
	#echo "9          9h"
	#echo "10         10h"
)
crash_if_nonzero_exit 'echo "$estimated_time_suggestions" | fzf --prompt="EXPECTED_WORK_HOURS -- $goal >" --header="HOURS	   AKA" $fzf_gap_arg'
estimated_time=$(dc --expression="2 k $(echo "$STDOUT" | awk '{print $1}') $PLANNING_FALLACY_PENALTY * p") 

taskdir=$TODOROOT/new/$goal
mkdir $taskdir
touch $taskdir/::$goal.hmm
touch $taskdir/:by_?
touch $taskdir/:time=${estimated_time}h
cat "$HERE"/log.do | sed "s:bash_utils:$HERE/bash_utils:g" > $taskdir/log.do
chmod +x $taskdir/log.do

do_it_now_cutoff=0.25	#15 minutes
if (( $(echo "$estimated_time <= $do_it_now_cutoff" | bc -l) )); then #if the goal can be done quickly, do it now
	"$HERE"/mark $taskdir 0_now
	taskdir=$(find "$TODOROOT/0_now" -type f -name "$goal.hmm" -exec dirname {} \; | head -n 1)
fi

echo $taskdir
